server:
  port: 8083

spring:
  application:
    name: car-rental-service

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

external:
  api:
    cars-url: https://raw.githubusercontent.com/vega/vega-datasets/master/data/cars.json
    max-results: 10
