services:
  discovery-service:
    image: iamnotsnani/discovery-service:latest
    container_name: discovery-service
    restart: unless-stopped
    ports:
      - "8761:8761"
    networks:
      - travel-network

  flight-service:
    image: iamnotsnani/flight-service:latest
    container_name: flight-service
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - SPRING_APPLICATION_NAME=flight-service
    depends_on:
      - discovery-service
    networks:
      - travel-network

  hotel-service:
    image: iamnotsnani/hotel-service:latest
    container_name: hotel-service
    restart: unless-stopped
    ports:
      - "8082:8082"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - SPRING_APPLICATION_NAME=hotel-service
    depends_on:
      - discovery-service
    networks:
      - travel-network

  car-rental-service:
    image: iamnotsnani/car-rental-service:latest
    container_name: car-rental-service
    restart: unless-stopped
    ports:
      - "8083:8083"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - SPRING_APPLICATION_NAME=car-rental-service
    depends_on:
      - discovery-service
    networks:
      - travel-network

  api-gateway:
    image: iamnotsnani/api-gateway:latest
    container_name: api-gateway
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - SPRING_APPLICATION_NAME=api-gateway
    depends_on:
      - discovery-service
    networks:
      - travel-network

networks:
  travel-network:
    driver: bridge
