server:
  port: 8080
  error:
    path: /error


spring:
  application:
    name: api-gateway

eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://localhost:8761/eureka/

ribbon:
  ConnectTimeout: 5000
  ReadTimeout: 15000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

zuul:
  set-content-wrapper: true
  routes:
    flights:
      path: /flights/**
      serviceId: flight-service
      strip-prefix: false
    hotels:
      path: /hotels/**
      serviceId: hotel-service
      strip-prefix: false
    cars:
      path: /cars/**
      serviceId: car-rental-service
      strip-prefix: false
