server:
  port: 8081

spring:
  application:
    name: flight-service


eureka:
  instance:
    # Force Eureka to use the IP address (127.0.0.1) instead of the Hostname
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

external:
  api:
    routes-url: https://raw.githubusercontent.com/jpatokal/openflights/master/data/routes.dat
    airlines-url: https://raw.githubusercontent.com/jpatokal/openflights/master/data/airlines.dat
    max-results: 10
