server:
  port: 8082

spring:
  application:
    name: hotel-service


eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

external:
  api:
    hotels-url: https://raw.githubusercontent.com/Lemoncode/simple-hotels-mock-rest-api/master/mock-data/hotels-data.json
    max-results: 10
